{% set version = "21.1.8" %}

package:
  name: flang-activation
  version: {{ version }}

source:
  # unused, but helpful so the bot creates updates automatically;
  # we use the _signature_, which is tiny and thus much faster to download
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "-rc") }}.src.tar.xz.sig
  sha256: ee44b67f2260fd87d40377560672ac0562bf9dc335b89d3c35edc41faa350424

build:
  number: 0
  # TODO: Skipping osx until flang is available.
  skip: true  # [osx]

outputs:
  - name: flang_impl_{{ cross_target_platform }}
    script: install_flang_impl.sh   # [unix]
    script: install_flang_impl.bat  # [win]
    # we don't cross-compile on windows -> no symlinks
    requirements:
      - flang ={{ version }}
      - flang-rt_{{ cross_target_platform }} ={{ version }}  # Fortran runtime (new in LLVM 21)
      - lld                     # [win]
      # for llvm-ar.exe
      - llvm-tools              # [win]
      - compiler-rt ={{ version }}
    test:
      commands:
        - {{ CBUILD }}-flang --version  # [unix]
        - {{ CHOST }}-flang --version   # [unix]
        - flang --version               # [win]

  - name: flang_{{ cross_target_platform }}
    script: install_flang.sh  # [unix]
    script: install_flang.bat  # [win]
    run_exports:
      strong:   # [unix]
        - libflang-rt >={{ version }}  # [unix]  # Changed from libflang in LLVM 21
    requirements:
      build:
        - sed       # [unix]
        - m2-sed    # [win]
      run:
        - {{ pin_subpackage("flang_impl_" ~ cross_target_platform, exact=True) }}
    test:
      files:
        - hello_world.f90
      commands:
        # on linux we point FC to the symlink; on windows, we point to the binary
        - $FC hello_world.f90       # [unix]
        - "%FC% hello_world.f90"    # [win]
        - ./a.out   # [unix]
        - a.exe     # [win]

about:
  home: https://flang.llvm.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Flang is a Fortran compiler targeting LLVM.
  description: |
    Flang is a modern Fortran compiler targeting LLVM. This package provides
    activation scripts and compiler wrappers that enable the use of Flang as
    the Fortran compiler in conda environments. It includes platform-specific
    configurations for cross-compilation support and ensures proper integration
    with the conda build system for Fortran projects.
  doc_url: https://flang.llvm.org
  dev_url: https://github.com/llvm/llvm-project

extra:
  recipe-maintainers:
    - isuruf
    - h-vetinari
